---
title: "STAA 566 GitHub Example"
author: "Ander Wilson"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## R Code

```{r}
library(tidyverse)
library(ggthemes)

# download one year of data
download1year <- function(year,poll){
  # download and read data
  filename <- paste0("daily_",poll,"_",year)
  download.file(paste0("https://aqs.epa.gov/aqsweb/airdata/",filename,".zip"), paste0(filename,".zip") )
  unzip(paste0(filename,".zip"))
  datain <- read_csv(paste0(filename,".csv"))
  
  # filter to Larimer County Colorado
  datain <- datain %>% 
    filter(`State Name`=="Colorado" & `County Code`=="069") %>%
    select(`State Name`, `County Name`, `Site Num`, `Date Local`, `Arithmetic Mean`, `City Name`, `Local Site Name`, `Address`) %>%
    drop_na()
  
  # remove downloaded files
  file.remove(paste0(filename,".zip"))
  file.remove(paste0(filename,".csv"))
  
  return(datain)
}

# loop through and download all years
lp_temp <- NULL
for(year in 1980:2021){
  lp_temp <- bind_rows(lp_temp, download1year(year,poll="TEMP"))
}

# rename without spaces in column names
colnames(lp_temp) <- c("State","County","SiteNum","Date","Temp","City","SiteName","Address")

# summarize data for years prior to 2021
lp_temp <- lp_temp %>% 
  mutate(month = lubridate::month(Date, label = TRUE), 
         year = lubridate::year(Date)) %>%
  filter(SiteNum == "0007") %>%
  group_by(year,month) %>%
  summarise(Temp = mean(Temp))
  

p_temp <- ggplot() + 
  geom_line(data=lp_temp %>% filter(year!=2020), 
            aes(x=month, y=Temp, group=year),
            color="grey70", alpha=.3) + 
  geom_line(data=lp_temp %>% filter(year==2021), 
            aes(x=month, y=Temp, group=year),
            color="red") + 
  geom_point(data=lp_temp %>% filter(year==2021), 
            aes(x=month, y=Temp, group=year),
            color="red")


p_temp <- p_temp + theme_minimal(base_size=12)
p_temp <- p_temp + ylab(expression("Average temperature ("*degree*"F)"))
p_temp <- p_temp + labs(title = "Monthly Average Temperature on Longs Peak from 1980-2021",
              subtitle=str_wrap(paste0("Based on daily average temperature data from the US Environmental Protection Agency. All data are from monitor site number 0007. Data downloaded on "
                                       ,format(lubridate::today(),  format = '%B %d %Y'),".")))
p_temp <- p_temp + theme(panel.grid.major.x = element_blank(),
               panel.grid.minor.y = element_blank(),
               panel.grid.major.y = element_line(linetype = 3, color="grey80"),
               axis.title.x = element_blank(),
               plot.subtitle = element_text(color="grey30"))

p_temp <- p_temp + ggrepel::geom_label_repel(data=lp_temp %>% filter(year==2021 & month==max(month)),
                              aes(x=month, y=Temp, label = year),
                 nudge_x = .5,
                 color="red",
                 label.size=NA,
                 segment.color = NA)
```

## Save Figure as pdf

```{r save as pdf}
pdf("LongsPeak.pdf", heigh=6, width=8)
print(p_temp)
dev.off()
```

## Display Figure in HTLM

```{r diplay}
p_temp
```